version: "3.8"

services:
  spring-boot-app:
    image: studentapi:latest  # Use your image name
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    ports:
      - "8081:8081"  # Expose port 8081
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # Any environment variables needed for the app
    networks:
      - monitoring
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    networks:
      - monitoring
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml

networks:
  app-network:
    driver: overlay
  monitoring:
    driver: bridge
