global:
  scrape_interval: 15s  # Set the scrape interval to 15 seconds
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'studentapi-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['studentapi-app:8081']  # Scraping the Spring Boot app

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
  # Rules to trigger alerts based on conditions
rule_files:
  - /etc/prometheus/alert.rules.yml
